import { Expense, ExpenseCategory } from '@/types';
import { formatCurrency, formatDate } from './formatters';
import { calculateSummary } from './calculations';

export const exportToCSV = (expenses: Expense[]): void => {
  const headers = ['Date', 'Category', 'Description', 'Amount'];
  const rows = expenses.map(expense => [
    formatDate(expense.date),
    expense.category,
    expense.description,
    expense.amount.toString(),
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  link.setAttribute('href', url);
  link.setAttribute('download', `expenses_${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportToMarkdown = (expenses: Expense[]): void => {
  if (expenses.length === 0) return;

  const summary = calculateSummary(expenses);
  const sortedExpenses = [...expenses].sort((a, b) =>
    new Date(b.date).getTime() - new Date(a.date).getTime()
  );

  // Get date range
  const oldestDate = sortedExpenses[sortedExpenses.length - 1].date;
  const newestDate = sortedExpenses[0].date;
  const dateRange = oldestDate === newestDate
    ? formatDate(oldestDate)
    : `${formatDate(oldestDate)} - ${formatDate(newestDate)}`;

  // Create visual bars for category breakdown
  const maxAmount = Math.max(...Object.values(summary.categoryBreakdown));
  const createBar = (amount: number) => {
    const percentage = maxAmount > 0 ? (amount / maxAmount) * 100 : 0;
    const barLength = Math.round(percentage / 5);
    return '█'.repeat(barLength) + '░'.repeat(20 - barLength);
  };

  // Build markdown content
  const lines: string[] = [
    '# Expense Report',
    '',
    `**Period:** ${dateRange}  `,
    `**Generated:** ${formatDate(new Date().toISOString())}  `,
    `**Total Transactions:** ${expenses.length}`,
    '',
    '---',
    '',
    '## Summary',
    '',
    `- **Total Spending:** ${formatCurrency(summary.totalSpending)}`,
    `- **Monthly Spending:** ${formatCurrency(summary.monthlySpending)}`,
    summary.topCategory
      ? `- **Top Category:** ${summary.topCategory.category} (${formatCurrency(summary.topCategory.amount)})`
      : '',
    '',
    '## Spending by Category',
    ''
  ];

  // Add category breakdown with bars
  const categories: ExpenseCategory[] = ['Food', 'Transportation', 'Entertainment', 'Shopping', 'Bills', 'Other'];
  categories.forEach(category => {
    const amount = summary.categoryBreakdown[category];
    if (amount > 0) {
      const bar = createBar(amount);
      const percentage = ((amount / summary.totalSpending) * 100).toFixed(1);
      lines.push(`**${category}**  `);
      lines.push(`\`${bar}\` ${formatCurrency(amount)} (${percentage}%)  `);
      lines.push('');
    }
  });

  lines.push('---', '', '## Transactions', '');

  // Group expenses by month
  const expensesByMonth = new Map<string, Expense[]>();
  sortedExpenses.forEach(expense => {
    const date = new Date(expense.date);
    const monthKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
    const monthName = date.toLocaleDateString('en-US', { year: 'numeric', month: 'long' });

    if (!expensesByMonth.has(monthKey)) {
      expensesByMonth.set(monthKey, []);
    }
    expensesByMonth.get(monthKey)?.push(expense);
  });

  // Sort months in descending order
  const sortedMonths = Array.from(expensesByMonth.entries()).sort((a, b) => b[0].localeCompare(a[0]));

  sortedMonths.forEach(([monthKey, monthExpenses]) => {
    const monthName = new Date(monthKey + '-01').toLocaleDateString('en-US', { year: 'numeric', month: 'long' });
    const monthTotal = monthExpenses.reduce((sum, e) => sum + e.amount, 0);

    lines.push(`### ${monthName}`);
    lines.push('');
    lines.push(`*Total: ${formatCurrency(monthTotal)}*`);
    lines.push('');
    lines.push('| Date | Category | Description | Amount |');
    lines.push('|------|----------|-------------|--------|');

    monthExpenses.forEach(expense => {
      const date = formatDate(expense.date).replace(/,/g, '');
      lines.push(`| ${date} | ${expense.category} | ${expense.description} | ${formatCurrency(expense.amount)} |`);
    });

    lines.push('');
  });

  lines.push('---', '', '*Generated by Expense Tracker*');

  const markdownContent = lines.join('\n');

  // Download the file
  const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  link.setAttribute('href', url);
  link.setAttribute('download', `expense-report_${new Date().toISOString().split('T')[0]}.md`);
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
